### ISSUE TITLE
Power to Raspberry Pi does not cut off on shutdown - RetroPie 4.8

### ISSUE THREAD

**Issue by georgevoliveira** [DeskPi-Team/deskpi_v1#3]
Greetings,

When the system is shutdown from terminal or EmulationStation, on Retropie, the adapter board does not cut power off to the Raspberry Pi.

If i double click the power button, the adapter board does issue a shutdown command to the Pi and cuts power after shutdown.

There were no errors when installing via install.sh script.

Thank you. Best regards

**Comment by jsProj** [comment]
After the pi is off, would a single click turn it back on? And does it immediate power on when plugged in?

**Comment by yoyojacky** [comment]
> There were no errors when installing via install.sh script.
> 
> Thank you. Best regards

Could you please try to send "poweroff" to /dev/ttyUSB0 serial port and see if the power button will turn to red color from blue color ?

**Comment by yoyojacky** [comment]
> After the pi is off, would a single click turn it back on? And does it immediate power on when plugged in?

1. yes.
2. if you turn "always on" switch to "EN" side , it will immedate power on when plugged in.
